version: '3.8'

services:
  db:
    image: postgres:15-alpine  # 가볍고 안정적인 버전
    container_name: seven-postgres
    ports:
      - "5432:5432"  # 내 컴퓨터 5432 포트와 연결
    environment:
      - POSTGRES_USER=myuser      
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=seven_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # DB 꺼도 데이터 안 날아가게 저장
    restart: always

volumes:
  postgres_data: